server:
  port: 8007
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@120.48.9.61:1521:xe
    username: liuzheng
    password: 102355


mybatis:
  # model的包
  type-aliases-package: com.lz.rhapi.pojo
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: on

# 打印sql

logging:
  level: debug

