server:
  port: 8085

dubbo:
  application:
    #注册在注册中心的名称，唯一标识，请勿重复
    name: provider
    id: provider
  #单zookeeper服务：zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://120.48.9.61:2181
    timeout: 10000
  #暴露服务方式
  protocol:
    id: dubbo
    #默认名称，勿修改
    name: dubbo
    #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
    port: 20880


  scan:
    base-packages: com.lz.rhprovider.Service




