server:
  port: 8085

dubbo:
  application:
    #注册在注册中心的名称，唯一标识，请勿重复
    name: user-provider
    id: user-provider

  #单zookeeper服务：zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://120.48.9.61:2181
    timeout: 60000
  #暴露服务方式
  protocol:
    id: dubbo
    #默认名称，勿修改
    name: dubbo
    #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
    port: 20880
  provider:
    timeout: 10000

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@120.48.9.61:1521:xe
    username: liuzheng
    password: 102355

mybatis:
  # model的包
  type-aliases-package: com.lz.rhapi
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: on
  mapper-locations: classpath*:com/lz/userprovider/user/mapper/sqlMapperXml/*.xml

