FROM maven:3-openjdk-8
RUN mkdir -p /source
ADD . /source
WORKDIR /source
RUN mvn --batch-mode clean package -Dmaven.test.skip=true

FROM openjdk:8-jre
LABEL maintainer="dev@dubbo.apache.org"
COPY --from=0 /source/provider/target/provider.jar /app.jar


ENV JAVA_OPTS = ""

#ENTRYPOINT ["tini", "--", "/usr/local/bin/entrypoint.sh"]

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

EXPOSE 8083