# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true

    - name: Deploy
      uses: kostya-ten/ssh-server-deploy@v4 #使用ssh连接服务器
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        scp_source: README.md
        scp_target: /usr/local/docker/proj
        before_script: |
          ls
          pwd
        after_script: |
          pwd
          ls
          cd /usr/local/docker/proj
          ls 
          #rm -rf ./*
          #git clone https://github.com/IzumiSakai1995/rpghelper.git
          #cd rpghelper
          #mvn clear install -Dmaven.test.skip=true
          #docker-compose up -d --build

