# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true

    - name: Deploy
      uses: appleboy/ssh-action@master #使用ssh连接服务器
      with:
        host: 120.48.9.61
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: 22
        script: |
          cd /usr/local/docker/proj
          rm -rf ./*
          git clone https://github.com/IzumiSakai1995/rpghelper.git
          cd rpghelper
         #docker-compose up -d --build

